package forms;

import classes.Conexao;
import classes.Utilitarios;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Yanni
 */
public class FormCadastrarFuncionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormCadastrarFuncionario
     */
    
    Utilitarios u = new Utilitarios();
    
    public FormCadastrarFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCdFuncionario = new javax.swing.JLabel();
        txtCdFuncionario = new javax.swing.JTextField();
        lblNmFuncionario = new javax.swing.JLabel();
        txtNmFuncionario = new javax.swing.JTextField();
        lblCdCpfFuncionario = new javax.swing.JLabel();
        txtCdCpfFuncionario = new javax.swing.JFormattedTextField();
        lblCdTelefoneFuncionario = new javax.swing.JLabel();
        txtCdTelefoneFuncionario = new javax.swing.JFormattedTextField();
        lblCdUsuario = new javax.swing.JLabel();
        txtCdUsuario = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        txtNmCargo = new javax.swing.JTextField();
        lblNmCargo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastrar Funcionário");

        lblCdFuncionario.setText("Código:");

        txtCdFuncionario.setToolTipText("Digite o código do funcionário");

        lblNmFuncionario.setText("Nome:");

        txtNmFuncionario.setToolTipText("Digite o nome do funcionário");

        lblCdCpfFuncionario.setText("CPF:");

        try {
            txtCdCpfFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCdCpfFuncionario.setToolTipText("Digite o CPF do funcionário");

        lblCdTelefoneFuncionario.setText("Telefone:");

        try {
            txtCdTelefoneFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCdTelefoneFuncionario.setToolTipText("Digite o telefone do funcionário");

        lblCdUsuario.setText("Usuário:");

        txtCdUsuario.setToolTipText("Digite o código de usuário do funcionário (não obrigatório)");

        btnLimpar.setText("Limpar");
        btnLimpar.setToolTipText("Clique aqui para limpar os valores");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setToolTipText("Clique aqui para cadastrar o funcionário");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/procurar.png"))); // NOI18N
        btnPesquisar.setToolTipText("Clique aqui para pesquisar o usuário");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        txtNmCargo.setToolTipText("Digite o cargo do funcionário");

        lblNmCargo.setText("Cargo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCdUsuario)
                            .addComponent(lblCdTelefoneFuncionario)
                            .addComponent(lblCdCpfFuncionario)
                            .addComponent(lblNmFuncionario)
                            .addComponent(lblCdFuncionario)
                            .addComponent(lblNmCargo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCdFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNmFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCdCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCdTelefoneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtNmCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnCadastrar)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCdFuncionario)
                    .addComponent(txtCdFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNmFuncionario)
                    .addComponent(txtNmFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNmCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNmCargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCdCpfFuncionario)
                    .addComponent(txtCdCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCdTelefoneFuncionario)
                    .addComponent(txtCdTelefoneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCdUsuario)
                        .addComponent(txtCdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnLimpar))
                .addGap(47, 47, 47))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-399)/2, (screenSize.height-315)/2, 399, 315);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        u.limparTextFields(this);       
        txtCdCpfFuncionario.setValue("");
        txtCdTelefoneFuncionario.setValue("");
        txtCdFuncionario.requestFocus(); 
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnPesquisarActionPerformed
    {//GEN-HEADEREND:event_btnPesquisarActionPerformed
        FormSelecionarUsuario fsu = new FormSelecionarUsuario();
        this.getDesktopPane().add(fsu);
        fsu.setFrameIcon(new ImageIcon(getClass().getResource("/imagens/icon.png")));
        fsu.setVisible(true);
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCadastrarActionPerformed
    {//GEN-HEADEREND:event_btnCadastrarActionPerformed
        int cod;
        String nome;
        String cargo;
        String cpf;
        String tel;
        int user; 
        String sql; 
        
        try
        {
            cod = Integer.parseInt(txtCdFuncionario.getText());
            nome = txtNmFuncionario.getText();
            cargo = txtNmCargo.getText();
            cpf = txtCdCpfFuncionario.getText();//pega o valor
            tel = txtCdTelefoneFuncionario.getText();
            
            cpf = cpf.replaceAll("\\.", "").replaceAll("-", "");//tira os pontos e o traço
            tel = tel.replaceAll("\\(", "").replaceAll("\\)", "").replaceAll("-", "").replaceAll(" ", "");
            
            if(txtCdUsuario.getText().equals("")) 
            {//se não foi digitado nada no código
                sql = "INSERT INTO funcionario (cd_funcionario, nm_funcionario, cd_telefone_funcionario, cd_cpf_funcionario, nm_cargo_funcionario)"
                   + " VALUES(" + cod + ", UPPER('" + nome + "'), " + tel + ", " + cpf + ", UPPER('" + cargo + "'))" ;
            }
            else 
            {                
                user = Integer.parseInt(txtCdUsuario.getText());
                sql = "INSERT INTO funcionario VALUES(" + cod + ", UPPER('" + nome + "'), " + tel + ", " + cpf + ", UPPER('" + cargo + "'), " + user + ")" ;
            } 
            
            if(Conexao.atualizar(sql) == -1)
            {
                JOptionPane.showMessageDialog(null, "O registro não pode ser inserido: \n" + Conexao.getErro(), "Cadastro", 0);
                btnLimparActionPerformed(evt);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso.", "Cadastro", 1);
                btnLimparActionPerformed(evt);  
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Erro: \n" + e.getMessage(), "Erro!", 0);
            u.limparTextFields(this);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel lblCdCpfFuncionario;
    private javax.swing.JLabel lblCdFuncionario;
    private javax.swing.JLabel lblCdTelefoneFuncionario;
    private javax.swing.JLabel lblCdUsuario;
    private javax.swing.JLabel lblNmCargo;
    private javax.swing.JLabel lblNmFuncionario;
    private javax.swing.JFormattedTextField txtCdCpfFuncionario;
    private javax.swing.JTextField txtCdFuncionario;
    private javax.swing.JFormattedTextField txtCdTelefoneFuncionario;
    private javax.swing.JTextField txtCdUsuario;
    private javax.swing.JTextField txtNmCargo;
    private javax.swing.JTextField txtNmFuncionario;
    // End of variables declaration//GEN-END:variables
}
